/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MeetingsList {
    }
}
declare global {
    interface HTMLMeetingsListElement extends Components.MeetingsList, HTMLStencilElement {
    }
    var HTMLMeetingsListElement: {
        prototype: HTMLMeetingsListElement;
        new (): HTMLMeetingsListElement;
    };
    interface HTMLElementTagNameMap {
        "meetings-list": HTMLMeetingsListElement;
    }
}
declare namespace LocalJSX {
    interface MeetingsList {
    }
    interface IntrinsicElements {
        "meetings-list": MeetingsList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "meetings-list": LocalJSX.MeetingsList & JSXBase.HTMLAttributes<HTMLMeetingsListElement>;
        }
    }
}
